FROM tomcat:9.0-jdk17-temurin

# Working directory in container
WORKDIR /usr/local/tomcat

# Remove default apps
RUN rm -rf webapps/*

# Copy full webapp folder from your project root
COPY ./webapp/ ./webapps/ROOT/

# Copy compiled classes
COPY ./build/classes/ ./WEB-INF/classes/

# Expose port
EXPOSE 8080

# Start Tomcat
CMD ["catalina.sh", "run"]
